name: postel
channels:
  - pyg
  - pytorch
  - dglteam/label/cu116
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - cryptography=41.0.7
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.3.101
  - cuda-libraries=11.6.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.3.101
  - cuda-nsight-compute=12.3.2
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.3.101
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.3.101
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=12.3.101
  - cuda-runtime=11.6.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.3.101
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - dgl=2.0.0.cu116
  - ffmpeg=4.3
  - freetype=2.12.1
  - gds-tools=1.8.1.2
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.9.2.110
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.1.112
  - libcufft-dev=10.7.1.112
  - libcufile=1.8.1.2
  - libcufile-dev=1.8.1.2
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcusolver=11.3.4.124
  - libcusparse=11.7.2.124
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.6.3.124
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.6.2.124
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - nsight-compute=2023.3.1.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.1
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - pooch=1.7.0
  - psutil=5.9.0
  - pycparser=2.21
  - pyg=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.18
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.0
  - pytorch-sparse=0.6.15
  - readline=8.2
  - requests=2.31.0
  - scipy=1.10.1
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.65.0
  - typing_extensions=4.7.1
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - appdirs==1.4.4
    - asttokens==2.4.1
    - backcall==0.2.0
    - cachetools==5.3.2
    - click==8.1.7
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==3.0.8
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - dotmap==1.3.30
    - eigency==1.77
    - executing==2.0.1
    - fonttools==4.47.0
    - gitdb==4.0.11
    - gitpython==3.1.40
    - google-auth==2.27.0
    - google-auth-oauthlib==1.0.0
    - googledrivedownloader==0.4
    - grpcio==1.60.0
    - importlib-metadata==7.0.1
    - importlib-resources==6.1.1
    - ipython==8.12.3
    - jedi==0.19.1
    - kiwisolver==1.4.5
    - littleutils==0.2.2
    - markdown==3.5.2
    - matplotlib==3.7.4
    - matplotlib-inline==0.1.6
    - oauthlib==3.2.2
    - ogb==1.3.6
    - outdated==0.2.2
    - pandas==2.0.3
    - parso==0.8.3
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.43
    - protobuf==4.25.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pygcl==0.1.2
    - pygments==2.17.2
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.3.2
    - seaborn==0.13.1
    - sentry-sdk==1.39.1
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - stack-data==0.6.3
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - torchdiffeq==0.2.3
    - traitlets==5.14.1
    - tzdata==2023.4
    - wandb==0.16.1
    - wcwidth==0.2.13
    - werkzeug==3.0.1
    - zipp==3.17.0
prefix: ~/anaconda3/envs/postel
